remote_theme: ctrlaltdev/ctrlaltdev-theme
theme_settings:
  title: "LMGTFY Queries"
  description: "Let Me Google That For You search queries (3M+ of them)"
github: "ctrlaltdev/LMGTFY-queries"
sass:
  sass_dir: _sass
  style: :compressed
